package chord.program.reflect;

/**
 * Kinds of events generated by dynamic analysis for resolving reflection.
 *
 * @author Mayur Naik (mhn@cs.stanford.edu)
 */
public class ReflectEventKind {
	public static final byte CLS_FOR_NAME_CALL = 0;
	public static final byte OBJ_NEW_INST_CALL = 1;
	public static final byte CON_NEW_INST_CALL = 2;
	public static final byte ARY_NEW_INST_CALL = 3;
}

