/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_sf_javabdd_BuDDyFactory */

#ifndef _Included_net_sf_javabdd_BuDDyFactory
#define _Included_net_sf_javabdd_BuDDyFactory
#ifdef __cplusplus
extern "C" {
#endif
#undef net_sf_javabdd_BuDDyFactory_USE_FINALIZER
#define net_sf_javabdd_BuDDyFactory_USE_FINALIZER 0L
/*
 * Class:     net_sf_javabdd_BuDDyFactory
 * Method:    registerNatives
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_sf_javabdd_BuDDyFactory_registerNatives
  (JNIEnv *, jclass);

/*
 * Class:     net_sf_javabdd_BuDDyFactory
 * Method:    buildCube0
 * Signature: (I[I)I
 */
JNIEXPORT jint JNICALL Java_net_sf_javabdd_BuDDyFactory_buildCube0
  (JNIEnv *, jclass, jint, jintArray);

/*
 * Class:     net_sf_javabdd_BuDDyFactory
 * Method:    buildCube1
 * Signature: (I[I)I
 */
JNIEXPORT jint JNICALL Java_net_sf_javabdd_BuDDyFactory_buildCube1
  (JNIEnv *, jclass, jint, jintArray);

/*
 * Class:     net_sf_javabdd_BuDDyFactory
 * Method:    makeSet0
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_net_sf_javabdd_BuDDyFactory_makeSet0
  (JNIEnv *, jclass, jintArray);

/*
 * Class:     net_sf_javabdd_BuDDyFactory
 * Method:    initialize0
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_net_sf_javabdd_BuDDyFactory_initialize0
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_sf_javabdd_BuDDyFactory
 * Method:    isInitialized0
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_net_sf_javabdd_BuDDyFactory_isInitialized0
  (JNIEnv *, jclass);

/*
 * Class:     net_sf_javabdd_BuDDyFactory
 * Method:    done0
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_sf_javabdd_BuDDyFactory_done0
  (JNIEnv *, jclass);

/*
 * Class:     net_sf_javabdd_BuDDyFactory
 * Method:    setError0
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_sf_javabdd_BuDDyFactory_setError0
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_sf_javabdd_BuDDyFactory
 * Method:    clearError0
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_sf_javabdd_BuDDyFactory_clearError0
  (JNIEnv *, jclass);

/*
 * Class:     net_sf_javabdd_BuDDyFactory
 * Method:    setMaxNodeNum0
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_sf_javabdd_BuDDyFactory_setMaxNodeNum0
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_sf_javabdd_BuDDyFactory
 * Method:    setMinFreeNodes0
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_sf_javabdd_BuDDyFactory_setMinFreeNodes0
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_sf_javabdd_BuDDyFactory
 * Method:    setMaxIncrease0
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_sf_javabdd_BuDDyFactory_setMaxIncrease0
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_sf_javabdd_BuDDyFactory
 * Method:    setIncreaseFactor0
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_net_sf_javabdd_BuDDyFactory_setIncreaseFactor0
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     net_sf_javabdd_BuDDyFactory
 * Method:    setCacheRatio0
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_sf_javabdd_BuDDyFactory_setCacheRatio0
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_sf_javabdd_BuDDyFactory
 * Method:    setNodeTableSize0
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_sf_javabdd_BuDDyFactory_setNodeTableSize0
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_sf_javabdd_BuDDyFactory
 * Method:    setCacheSize0
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_sf_javabdd_BuDDyFactory_setCacheSize0
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_sf_javabdd_BuDDyFactory
 * Method:    varNum0
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_sf_javabdd_BuDDyFactory_varNum0
  (JNIEnv *, jclass);

/*
 * Class:     net_sf_javabdd_BuDDyFactory
 * Method:    setVarNum0
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_sf_javabdd_BuDDyFactory_setVarNum0
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_sf_javabdd_BuDDyFactory
 * Method:    duplicateVar0
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_sf_javabdd_BuDDyFactory_duplicateVar0
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_sf_javabdd_BuDDyFactory
 * Method:    extVarNum0
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_sf_javabdd_BuDDyFactory_extVarNum0
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_sf_javabdd_BuDDyFactory
 * Method:    ithVar0
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_sf_javabdd_BuDDyFactory_ithVar0
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_sf_javabdd_BuDDyFactory
 * Method:    nithVar0
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_sf_javabdd_BuDDyFactory_nithVar0
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_sf_javabdd_BuDDyFactory
 * Method:    swapVar0
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_net_sf_javabdd_BuDDyFactory_swapVar0
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_sf_javabdd_BuDDyFactory
 * Method:    makePair0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_sf_javabdd_BuDDyFactory_makePair0
  (JNIEnv *, jclass);

/*
 * Class:     net_sf_javabdd_BuDDyFactory
 * Method:    printAll0
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_sf_javabdd_BuDDyFactory_printAll0
  (JNIEnv *, jclass);

/*
 * Class:     net_sf_javabdd_BuDDyFactory
 * Method:    printTable0
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_sf_javabdd_BuDDyFactory_printTable0
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_sf_javabdd_BuDDyFactory
 * Method:    load0
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_net_sf_javabdd_BuDDyFactory_load0
  (JNIEnv *, jclass, jstring);

/*
 * Class:     net_sf_javabdd_BuDDyFactory
 * Method:    save0
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_net_sf_javabdd_BuDDyFactory_save0
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     net_sf_javabdd_BuDDyFactory
 * Method:    level2Var0
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_sf_javabdd_BuDDyFactory_level2Var0
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_sf_javabdd_BuDDyFactory
 * Method:    var2Level0
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_sf_javabdd_BuDDyFactory_var2Level0
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_sf_javabdd_BuDDyFactory
 * Method:    reorder0
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_sf_javabdd_BuDDyFactory_reorder0
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_sf_javabdd_BuDDyFactory
 * Method:    autoReorder0
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_sf_javabdd_BuDDyFactory_autoReorder0
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_sf_javabdd_BuDDyFactory
 * Method:    autoReorder1
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_net_sf_javabdd_BuDDyFactory_autoReorder1
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_sf_javabdd_BuDDyFactory
 * Method:    getReorderMethod0
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_sf_javabdd_BuDDyFactory_getReorderMethod0
  (JNIEnv *, jclass);

/*
 * Class:     net_sf_javabdd_BuDDyFactory
 * Method:    getReorderTimes0
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_sf_javabdd_BuDDyFactory_getReorderTimes0
  (JNIEnv *, jclass);

/*
 * Class:     net_sf_javabdd_BuDDyFactory
 * Method:    disableReorder0
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_sf_javabdd_BuDDyFactory_disableReorder0
  (JNIEnv *, jclass);

/*
 * Class:     net_sf_javabdd_BuDDyFactory
 * Method:    enableReorder0
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_sf_javabdd_BuDDyFactory_enableReorder0
  (JNIEnv *, jclass);

/*
 * Class:     net_sf_javabdd_BuDDyFactory
 * Method:    reorderVerbose0
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_sf_javabdd_BuDDyFactory_reorderVerbose0
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_sf_javabdd_BuDDyFactory
 * Method:    setVarOrder0
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_net_sf_javabdd_BuDDyFactory_setVarOrder0
  (JNIEnv *, jclass, jintArray);

/*
 * Class:     net_sf_javabdd_BuDDyFactory
 * Method:    addVarBlock0
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_net_sf_javabdd_BuDDyFactory_addVarBlock0
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     net_sf_javabdd_BuDDyFactory
 * Method:    addVarBlock1
 * Signature: (IIZ)V
 */
JNIEXPORT void JNICALL Java_net_sf_javabdd_BuDDyFactory_addVarBlock1
  (JNIEnv *, jclass, jint, jint, jboolean);

/*
 * Class:     net_sf_javabdd_BuDDyFactory
 * Method:    varBlockAll0
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_sf_javabdd_BuDDyFactory_varBlockAll0
  (JNIEnv *, jclass);

/*
 * Class:     net_sf_javabdd_BuDDyFactory
 * Method:    clearVarBlocks0
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_sf_javabdd_BuDDyFactory_clearVarBlocks0
  (JNIEnv *, jclass);

/*
 * Class:     net_sf_javabdd_BuDDyFactory
 * Method:    printOrder0
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_sf_javabdd_BuDDyFactory_printOrder0
  (JNIEnv *, jclass);

/*
 * Class:     net_sf_javabdd_BuDDyFactory
 * Method:    nodeCount0
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_net_sf_javabdd_BuDDyFactory_nodeCount0
  (JNIEnv *, jclass, jintArray);

/*
 * Class:     net_sf_javabdd_BuDDyFactory
 * Method:    getAllocNum0
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_sf_javabdd_BuDDyFactory_getAllocNum0
  (JNIEnv *, jclass);

/*
 * Class:     net_sf_javabdd_BuDDyFactory
 * Method:    getCacheSize0
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_sf_javabdd_BuDDyFactory_getCacheSize0
  (JNIEnv *, jclass);

/*
 * Class:     net_sf_javabdd_BuDDyFactory
 * Method:    getNodeNum0
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_sf_javabdd_BuDDyFactory_getNodeNum0
  (JNIEnv *, jclass);

/*
 * Class:     net_sf_javabdd_BuDDyFactory
 * Method:    reorderGain0
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_sf_javabdd_BuDDyFactory_reorderGain0
  (JNIEnv *, jclass);

/*
 * Class:     net_sf_javabdd_BuDDyFactory
 * Method:    printStat0
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_sf_javabdd_BuDDyFactory_printStat0
  (JNIEnv *, jclass);

/*
 * Class:     net_sf_javabdd_BuDDyFactory
 * Method:    getVersion0
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_sf_javabdd_BuDDyFactory_getVersion0
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class net_sf_javabdd_BuDDyFactory_BuDDyBDDBitVector */

#ifndef _Included_net_sf_javabdd_BuDDyFactory_BuDDyBDDBitVector
#define _Included_net_sf_javabdd_BuDDyFactory_BuDDyBDDBitVector
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class net_sf_javabdd_BuDDyFactory_BuDDyBDDPairingWithFinalizer */

#ifndef _Included_net_sf_javabdd_BuDDyFactory_BuDDyBDDPairingWithFinalizer
#define _Included_net_sf_javabdd_BuDDyFactory_BuDDyBDDPairingWithFinalizer
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class net_sf_javabdd_BuDDyFactory_BuDDyBDDPairing */

#ifndef _Included_net_sf_javabdd_BuDDyFactory_BuDDyBDDPairing
#define _Included_net_sf_javabdd_BuDDyFactory_BuDDyBDDPairing
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_sf_javabdd_BuDDyFactory_BuDDyBDDPairing
 * Method:    set0
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_net_sf_javabdd_BuDDyFactory_00024BuDDyBDDPairing_set0
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     net_sf_javabdd_BuDDyFactory_BuDDyBDDPairing
 * Method:    set1
 * Signature: (J[I[I)V
 */
JNIEXPORT void JNICALL Java_net_sf_javabdd_BuDDyFactory_00024BuDDyBDDPairing_set1
  (JNIEnv *, jclass, jlong, jintArray, jintArray);

/*
 * Class:     net_sf_javabdd_BuDDyFactory_BuDDyBDDPairing
 * Method:    set2
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_net_sf_javabdd_BuDDyFactory_00024BuDDyBDDPairing_set2
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     net_sf_javabdd_BuDDyFactory_BuDDyBDDPairing
 * Method:    set3
 * Signature: (J[I[I)V
 */
JNIEXPORT void JNICALL Java_net_sf_javabdd_BuDDyFactory_00024BuDDyBDDPairing_set3
  (JNIEnv *, jclass, jlong, jintArray, jintArray);

/*
 * Class:     net_sf_javabdd_BuDDyFactory_BuDDyBDDPairing
 * Method:    reset0
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_net_sf_javabdd_BuDDyFactory_00024BuDDyBDDPairing_reset0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_sf_javabdd_BuDDyFactory_BuDDyBDDPairing
 * Method:    free0
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_net_sf_javabdd_BuDDyFactory_00024BuDDyBDDPairing_free0
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class net_sf_javabdd_BuDDyFactory_BuDDyBDDDomain */

#ifndef _Included_net_sf_javabdd_BuDDyFactory_BuDDyBDDDomain
#define _Included_net_sf_javabdd_BuDDyFactory_BuDDyBDDDomain
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class net_sf_javabdd_BuDDyFactory_BuDDyBDDWithFinalizer */

#ifndef _Included_net_sf_javabdd_BuDDyFactory_BuDDyBDDWithFinalizer
#define _Included_net_sf_javabdd_BuDDyFactory_BuDDyBDDWithFinalizer
#ifdef __cplusplus
extern "C" {
#endif
#undef net_sf_javabdd_BuDDyFactory_BuDDyBDDWithFinalizer_INVALID_BDD
#define net_sf_javabdd_BuDDyFactory_BuDDyBDDWithFinalizer_INVALID_BDD -1L
#ifdef __cplusplus
}
#endif
#endif
/* Header for class net_sf_javabdd_BuDDyFactory_BuDDyBDD */

#ifndef _Included_net_sf_javabdd_BuDDyFactory_BuDDyBDD
#define _Included_net_sf_javabdd_BuDDyFactory_BuDDyBDD
#ifdef __cplusplus
extern "C" {
#endif
#undef net_sf_javabdd_BuDDyFactory_BuDDyBDD_INVALID_BDD
#define net_sf_javabdd_BuDDyFactory_BuDDyBDD_INVALID_BDD -1L
/*
 * Class:     net_sf_javabdd_BuDDyFactory_BuDDyBDD
 * Method:    var0
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_sf_javabdd_BuDDyFactory_00024BuDDyBDD_var0
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_sf_javabdd_BuDDyFactory_BuDDyBDD
 * Method:    high0
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_sf_javabdd_BuDDyFactory_00024BuDDyBDD_high0
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_sf_javabdd_BuDDyFactory_BuDDyBDD
 * Method:    low0
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_sf_javabdd_BuDDyFactory_00024BuDDyBDD_low0
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_sf_javabdd_BuDDyFactory_BuDDyBDD
 * Method:    not0
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_sf_javabdd_BuDDyFactory_00024BuDDyBDD_not0
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_sf_javabdd_BuDDyFactory_BuDDyBDD
 * Method:    ite0
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_net_sf_javabdd_BuDDyFactory_00024BuDDyBDD_ite0
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     net_sf_javabdd_BuDDyFactory_BuDDyBDD
 * Method:    relprod0
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_net_sf_javabdd_BuDDyFactory_00024BuDDyBDD_relprod0
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     net_sf_javabdd_BuDDyFactory_BuDDyBDD
 * Method:    compose0
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_net_sf_javabdd_BuDDyFactory_00024BuDDyBDD_compose0
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     net_sf_javabdd_BuDDyFactory_BuDDyBDD
 * Method:    constrain0
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_net_sf_javabdd_BuDDyFactory_00024BuDDyBDD_constrain0
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_sf_javabdd_BuDDyFactory_BuDDyBDD
 * Method:    exist0
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_net_sf_javabdd_BuDDyFactory_00024BuDDyBDD_exist0
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_sf_javabdd_BuDDyFactory_BuDDyBDD
 * Method:    forAll0
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_net_sf_javabdd_BuDDyFactory_00024BuDDyBDD_forAll0
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_sf_javabdd_BuDDyFactory_BuDDyBDD
 * Method:    unique0
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_net_sf_javabdd_BuDDyFactory_00024BuDDyBDD_unique0
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_sf_javabdd_BuDDyFactory_BuDDyBDD
 * Method:    restrict0
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_net_sf_javabdd_BuDDyFactory_00024BuDDyBDD_restrict0
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_sf_javabdd_BuDDyFactory_BuDDyBDD
 * Method:    simplify0
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_net_sf_javabdd_BuDDyFactory_00024BuDDyBDD_simplify0
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_sf_javabdd_BuDDyFactory_BuDDyBDD
 * Method:    support0
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_sf_javabdd_BuDDyFactory_00024BuDDyBDD_support0
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_sf_javabdd_BuDDyFactory_BuDDyBDD
 * Method:    apply0
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_net_sf_javabdd_BuDDyFactory_00024BuDDyBDD_apply0
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     net_sf_javabdd_BuDDyFactory_BuDDyBDD
 * Method:    applyAll0
 * Signature: (IIII)I
 */
JNIEXPORT jint JNICALL Java_net_sf_javabdd_BuDDyFactory_00024BuDDyBDD_applyAll0
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     net_sf_javabdd_BuDDyFactory_BuDDyBDD
 * Method:    applyEx0
 * Signature: (IIII)I
 */
JNIEXPORT jint JNICALL Java_net_sf_javabdd_BuDDyFactory_00024BuDDyBDD_applyEx0
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     net_sf_javabdd_BuDDyFactory_BuDDyBDD
 * Method:    applyUni0
 * Signature: (IIII)I
 */
JNIEXPORT jint JNICALL Java_net_sf_javabdd_BuDDyFactory_00024BuDDyBDD_applyUni0
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     net_sf_javabdd_BuDDyFactory_BuDDyBDD
 * Method:    satOne0
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_sf_javabdd_BuDDyFactory_00024BuDDyBDD_satOne0
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_sf_javabdd_BuDDyFactory_BuDDyBDD
 * Method:    fullSatOne0
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_sf_javabdd_BuDDyFactory_00024BuDDyBDD_fullSatOne0
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_sf_javabdd_BuDDyFactory_BuDDyBDD
 * Method:    satOne1
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_net_sf_javabdd_BuDDyFactory_00024BuDDyBDD_satOne1
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     net_sf_javabdd_BuDDyFactory_BuDDyBDD
 * Method:    printSet0
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_sf_javabdd_BuDDyFactory_00024BuDDyBDD_printSet0
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_sf_javabdd_BuDDyFactory_BuDDyBDD
 * Method:    printDot0
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_sf_javabdd_BuDDyFactory_00024BuDDyBDD_printDot0
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_sf_javabdd_BuDDyFactory_BuDDyBDD
 * Method:    nodeCount0
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_sf_javabdd_BuDDyFactory_00024BuDDyBDD_nodeCount0
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_sf_javabdd_BuDDyFactory_BuDDyBDD
 * Method:    pathCount0
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_net_sf_javabdd_BuDDyFactory_00024BuDDyBDD_pathCount0
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_sf_javabdd_BuDDyFactory_BuDDyBDD
 * Method:    satCount0
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_net_sf_javabdd_BuDDyFactory_00024BuDDyBDD_satCount0
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_sf_javabdd_BuDDyFactory_BuDDyBDD
 * Method:    satCount1
 * Signature: (II)D
 */
JNIEXPORT jdouble JNICALL Java_net_sf_javabdd_BuDDyFactory_00024BuDDyBDD_satCount1
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_sf_javabdd_BuDDyFactory_BuDDyBDD
 * Method:    logSatCount0
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_net_sf_javabdd_BuDDyFactory_00024BuDDyBDD_logSatCount0
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_sf_javabdd_BuDDyFactory_BuDDyBDD
 * Method:    logSatCount1
 * Signature: (II)D
 */
JNIEXPORT jdouble JNICALL Java_net_sf_javabdd_BuDDyFactory_00024BuDDyBDD_logSatCount1
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     net_sf_javabdd_BuDDyFactory_BuDDyBDD
 * Method:    varProfile0
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_net_sf_javabdd_BuDDyFactory_00024BuDDyBDD_varProfile0
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_sf_javabdd_BuDDyFactory_BuDDyBDD
 * Method:    addRef
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_sf_javabdd_BuDDyFactory_00024BuDDyBDD_addRef
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_sf_javabdd_BuDDyFactory_BuDDyBDD
 * Method:    delRef
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_sf_javabdd_BuDDyFactory_00024BuDDyBDD_delRef
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_sf_javabdd_BuDDyFactory_BuDDyBDD
 * Method:    veccompose0
 * Signature: (IJ)I
 */
JNIEXPORT jint JNICALL Java_net_sf_javabdd_BuDDyFactory_00024BuDDyBDD_veccompose0
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     net_sf_javabdd_BuDDyFactory_BuDDyBDD
 * Method:    replace0
 * Signature: (IJ)I
 */
JNIEXPORT jint JNICALL Java_net_sf_javabdd_BuDDyFactory_00024BuDDyBDD_replace0
  (JNIEnv *, jclass, jint, jlong);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class net_sf_javabdd_BuDDyFactory_BuDDyFactoryWithFinalizer */

#ifndef _Included_net_sf_javabdd_BuDDyFactory_BuDDyFactoryWithFinalizer
#define _Included_net_sf_javabdd_BuDDyFactory_BuDDyFactoryWithFinalizer
#ifdef __cplusplus
extern "C" {
#endif
#undef net_sf_javabdd_BuDDyFactory_BuDDyFactoryWithFinalizer_USE_FINALIZER
#define net_sf_javabdd_BuDDyFactory_BuDDyFactoryWithFinalizer_USE_FINALIZER 0L
#ifdef __cplusplus
}
#endif
#endif
